// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateAvatar(ctx context.Context, svg string) (Avatar, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolePermission, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Auth, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateValidationUser(ctx context.Context, arg CreateValidationUserParams) (UsersValidation, error)
	DeleteAvatar(ctx context.Context, id int32) (Avatar, error)
	DeletePermission(ctx context.Context, id int32) (Permission, error)
	DeleteRole(ctx context.Context, id int32) (Role, error)
	DeleteRolePermission(ctx context.Context, roleID int32) (RolePermission, error)
	DeleteUser(ctx context.Context, id int32) (User, error)
	GetAvatar(ctx context.Context, id int32) (Avatar, error)
	GetAvatars(ctx context.Context, arg GetAvatarsParams) ([]Avatar, error)
	GetPermission(ctx context.Context, id int32) (Permission, error)
	GetPermissionByInternalName(ctx context.Context, internalName string) (Permission, error)
	GetPermissions(ctx context.Context, arg GetPermissionsParams) ([]Permission, error)
	GetRole(ctx context.Context, id int32) (Role, error)
	GetRoleByInternalName(ctx context.Context, internalName string) (Role, error)
	GetRolePermission(ctx context.Context, id int32) ([]RolePermission, error)
	GetRolePermissionsByRole(ctx context.Context, roleID int32) ([]GetRolePermissionsByRoleRow, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error)
	GetTokenByUser(ctx context.Context, userID int32) (Auth, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserWithAvatar(ctx context.Context, id int32) (GetUserWithAvatarRow, error)
	GetUserWithRole(ctx context.Context, id int32) (GetUserWithRoleRow, error)
	GetUserWithRoleAndAvatar(ctx context.Context, id int32) (GetUserWithRoleAndAvatarRow, error)
	GetUserWithValidationUser(ctx context.Context, id int32) (GetUserWithValidationUserRow, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	GetUsersWithAvatar(ctx context.Context, arg GetUsersWithAvatarParams) ([]GetUsersWithAvatarRow, error)
	GetUsersWithRole(ctx context.Context, arg GetUsersWithRoleParams) ([]GetUsersWithRoleRow, error)
	GetUsersWithRoleAndAvatar(ctx context.Context, arg GetUsersWithRoleAndAvatarParams) ([]GetUsersWithRoleAndAvatarRow, error)
	GetValidationUser(ctx context.Context, userID int32) (UsersValidation, error)
	GetValidationUserByHash(ctx context.Context, hash string) (UsersValidation, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
	RevokeTokenByUser(ctx context.Context, userID int32) (Auth, error)
	UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) (Avatar, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserValidationUsed(ctx context.Context, id int32) (UsersValidation, error)
}

var _ Querier = (*Queries)(nil)
