FROM golang:1.22rc1-alpine

WORKDIR /api

RUN apk add --no-cache make

RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN ln -s /go/bin/linux_amd64/migrate /usr/local/bin/migrate

COPY ./api/go.mod ./api/go.sum ./
# COPY go.mod ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]