POST http://localhost:3000/api/v1/auth/token
content-type: application/json

    {
        "email": "admin@admin.com.br",
        "password": "admin"
    }

###

POST http://localhost:3000/api/v1/auth/token/refresh
content-type: application/json

    {
        "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjM3MzAsImlkIjoxfQ.gIIyI5HFon6bzYZu6zevY8xv5Kfyubo_cMC8ox79Rs0"
    }