GET http://localhost:3000/api/v1/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjM3MzAsImlkIjoxfQ.gIIyI5HFon6bzYZu6zevY8xv5Kfyubo_cMC8ox79Rs0

###
POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjM3MzAsImlkIjoxfQ.gIIyI5HFon6bzYZu6zevY8xv5Kfyubo_cMC8ox79Rs0

    {
        "name": "marcelo",
        "email": "marcelo@gmail.com",
        "password": "admin"
    }
###
GET http://localhost:3000/api/v1/user/6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjM3MzAsImlkIjoxfQ.gIIyI5HFon6bzYZu6zevY8xv5Kfyubo_cMC8ox79Rs0

###
PUT http://localhost:3000/api/v1/user/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjM3MzAsImlkIjoxfQ.gIIyI5HFon6bzYZu6zevY8xv5Kfyubo_cMC8ox79Rs0

    {
        "name": "jabiraca",
        "email": "jabiraca@jabiraca.com.br",
        "password": "admin"
    }

###
DELETE http://localhost:3000/api/v1/user/6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY2NjM3MzAsImlkIjoxfQ.gIIyI5HFon6bzYZu6zevY8xv5Kfyubo_cMC8ox79Rs0

