POST http://localhost:3000/api/v1/auth/token
content-type: application/json

    {
        "email": "admin@admin.com.br",
        "password": "admin"
    }

###

POST http://localhost:3000/api/v1/auth/token/refresh
content-type: application/json

    {
        "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzOTU2OTYsImlkIjoxfQ.319BkILD_U15jfn9nBlBsxnG-F6r0lHcW7hi2LZ-Nbc"
    }