GET http://localhost:3000/api/v1/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzODE1MTUsImlkIjoxfQ.R5X-Tm8Z8lcfNbPu-Q8C_OLtBPFLuIz2oDeXORXtpaU

###
POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzODE1MTUsImlkIjoxfQ.R5X-Tm8Z8lcfNbPu-Q8C_OLtBPFLuIz2oDeXORXtpaU

    {
        "name": "xibiuzin",
        "email": "marcelo@gmail.com",
        "password": "jabiraca"
    }
###

PUT http://localhost:3000/api/v1/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzODE1MTUsImlkIjoxfQ.R5X-Tm8Z8lcfNbPu-Q8C_OLtBPFLuIz2oDeXORXtpaU

    {
        "name": "jabiraco",
        "password": "jabiraca2",
        "email": "jabiraca@jabiraca.com"
    }

###
DELETE http://localhost:3000/api/v1/user/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzODE1MTUsImlkIjoxfQ.R5X-Tm8Z8lcfNbPu-Q8C_OLtBPFLuIz2oDeXORXtpaU

###
GET http://localhost:3000/api/v1/user/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzODE1MTUsImlkIjoxfQ.R5X-Tm8Z8lcfNbPu-Q8C_OLtBPFLuIz2oDeXORXtpaU
