GET http://localhost:3000/api/v1/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzOTU2OTYsImlkIjoxfQ.319BkILD_U15jfn9nBlBsxnG-F6r0lHcW7hi2LZ-Nbc

###
POST http://localhost:3000/api/v1/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzOTU2OTYsImlkIjoxfQ.319BkILD_U15jfn9nBlBsxnG-F6r0lHcW7hi2LZ-Nbc

    {
        "name": "marcelo",
        "email": "marcelo@gmail.com",
        "password": "admin"
    }
###
GET http://localhost:3000/api/v1/user/6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzOTU2OTYsImlkIjoxfQ.319BkILD_U15jfn9nBlBsxnG-F6r0lHcW7hi2LZ-Nbc

###
PUT http://localhost:3000/api/v1/user/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzOTU2OTYsImlkIjoxfQ.319BkILD_U15jfn9nBlBsxnG-F6r0lHcW7hi2LZ-Nbc

    {
        "name": "jabiraca",
        "email": "jabiraca@jabiraca.com.br",
        "password": "admin"
    }

###
DELETE http://localhost:3000/api/v1/user/6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDYzOTU2OTYsImlkIjoxfQ.319BkILD_U15jfn9nBlBsxnG-F6r0lHcW7hi2LZ-Nbc

